version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Chrome Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
      - run:
          name: Set CHROME_BIN env variable
          command: export CHROME_BIN=$(which google-chrome-stable)
      - run:
          name: Run tests
          command: npm test --passWithNoTests

  build-node:
    # Build node project
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts directory
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  deploy:
    # Example deploy job (not active in the workflow by default)
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '# e.g. ./deploy.sh'

workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
    # Uncomment the deploy step if needed in the workflow
    # - deploy:
    #     requires:
    #       - build-node
